
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'rishu_snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true

